version: '3'

services:
  task:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./orders.csv:/app/orders.csv
    environment:
      - PYTHONUNBUFFERED=1

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./orders.csv:/app/orders.csv
    command: >
      sh -c "pip install --no-cache-dir pytest && pytest -v"
